apiVersion: v1
kind: Service
metadata:
  name: trino-nlp-embeddings
spec:
  selector:
    app: trino-nlp-embeddings
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Port on the Minikube node
  type: NodePort
